// <auto-generated />
namespace MFSFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(category));
        
        string IMigrationMetadata.Id
        {
            get { return "201708112237155_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
